spring:
  data:
    redis:
      repositories:
        enabled: false

datasource:
  redis:
    database: 0
    master:
      host: ${REDIS_MASTER_HOST}
      port: ${REDIS_MASTER_PORT}
    replicas:
      - host: ${REDIS_REPLICA_1_HOST}
        port: ${REDIS_REPLICA_1_PORT}
  redis-cache:
    host: ${REDIS_CACHE_HOST}
    port: ${REDIS_CACHE_PORT}
    database: 0

---
spring.config.activate.on-profile: local, test

datasource:
  redis:
    master:
      host: localhost
      port: 6379
    replicas:
      - host: localhost
        port: 6380
  redis-cache:
    host: localhost
    port: 6381
    database: 0

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: qa

---
spring.config.activate.on-profile: prd